const StartTexts = [{
  name: 'Global climate changes',
  text: [['Today', ',', 'our', 'planet', 'is', 'in', 'serious', 'danger'],
    ['Ozone', 'layer', 'depletion', ',', 'extinction', 'of', 'animals', 'and', 'plants', ',', 'air', 'and', 'water', 'pollution', ',', 'deforestation', 'are', 'the', 'problems', 'that', 'threaten', 'our', 'life', 'on', 'the', 'Earth'],
    ['But', 'many', 'of', 'the', 'environmental', 'organizations', 'have', 'identified', 'global', 'climate', 'changes', 'as', 'one', 'of', 'the', 'greatest', 'threats', 'to', 'the', 'planet'],
    ['The', 'natural', 'greenhouse', 'effect', 'keeps', 'the', 'planet', '33', 'degrees', 'Celsius', 'warmer', 'than', 'it', 'would', 'otherwise', 'be'],
    ['Over', 'the', 'last', '200', 'years', 'human', 'activities', 'have', 'resulted', 'in', 'increasing', 'of', 'emissions', 'of', 'greenhouse', 'gases', 'and', 'therefor', 'the', 'earth`s', 'temperature', 'rising'],
    ['Scientists', 'have', 'projected', 'that', 'if', 'people', 'continue', 'to', 'alter', 'the', 'composition', 'of', 'the', 'atmosphere', ',', 'the', 'average', 'surface', 'temperatures', 'could', 'rise', 'between', '2', 'and', '3', 'degrees', 'Celsius', 'globally', 'over', 'the', 'next', '100', 'years'],
    ['This', 'rate', 'of', 'climatic', 'change', 'would', 'cause', 'significant', 'damage', 'to', 'ecological', 'systems', 'and', 'economies', 'on', 'a', 'global', 'scale'],
    ['The', 'only', 'way', 'to', 'solve', 'the', 'problem', 'is', 'to', 'stop', 'burning', 'fossil', 'fuels', 'and', 'to', 'start', 'using', 'clean', 'renewable', 'energy', ',', 'like', 'wind', 'or', 'solar', 'power'],
    ['But', 'such', 'conversion', 'to', 'new', 'energy', 'sources', 'is', 'not', 'an', 'easy', 'task'],
    ['Different', 'companies', 'continue', 'investing', 'money', 'in', 'new', 'oil', ',', 'coal', ',', 'gas', 'exploration', ',', 'despite', 'the', 'climate', 'threat'],
    ['And', 'although', 'governments', 'have', 'agreed', 'that', 'the', 'problem', 'is', 'serious', 'they', 'are', 'encouraging', 'these', 'companies', 'with', 'favourable', 'tax', 'rates'],
    ['Almost', 'every', 'year', 'industrialized', 'countries', 'sign', 'different', 'conventions', 'on', 'reducing', 'carbon', 'dioxide', 'and', 'other', 'emissions', ',', 'but', 'in', 'the', 'meantime', 'little', 'real', 'action', 'is', 'being', 'taken', 'to', 'address', 'the', 'problem'],
    ['All', 'over', 'the', 'world', 'people', 'join', 'international', 'organizations', ',', 'like', 'Greenpeace', ',', 'the', 'Nature', 'Conservancy', ',', 'WWF', ',', 'and', 'others', 'to', 'make', 'governments', 'face', 'up', 'to', 'their', 'responsibilities', 'and', 'protect', 'our', 'planet', 's', 'flora', 'and', 'fauna'],
    ['Nowadays', 'we', 'have', 'the', 'time', ',', 'the', 'money', 'and', 'even', 'the', 'technology', 'to', 'prevent', 'a', 'disaster'],
    ['But', 'we', 'should', 'always', 'remember', 'that', 'the', 'longer', 'action', 'is', 'delayed', ',', 'the', 'more', 'drastic', 'it', 'will', 'need', 'to', 'be']]
}, {
  name: 'Moscow`s environmental problems',
  text: [['The', 'development', 'of', 'Moscow', 'is', 'associated', 'with', 'high', 'density', 'housing', ',', 'intensive', 'development', 'of', 'the', 'suburbs', ',', 'rapid', 'expansion', 'and', 'modernization', 'of', 'transport', 'networks', 'and', 'road', 'infrastructure', ',', 'etc'],
    ['All', 'this', 'contributes', 'to', 'the', 'huge', 'impact', 'on', 'the', 'city`s', 'natural', 'systems', 'causing', 'significant', 'changes', 'in', 'their', 'structure', 'and', 'the', 'emergence', 'of', 'hazards', 'detrimental', 'to', 'the', 'population'],
    ['The', 'extremely', 'high', 'population', 'density', 'leads', 'to', 'increased', 'consumption', 'of', 'resources', ',', 'high', 'emissions', 'of', 'pollutants', 'and', 'results', 'in', 'the', 'adverse', 'effects', 'of', 'electromagnetic', 'and', 'radiation', 'fields', 'in', 'these', 'areas'],
    ['The', 'most', 'urgent', 'issues', 'are', 'the', 'scarcity', 'and', 'pollution', 'of', 'such', 'critical', 'resources', 'such', 'as', 'air', 'and', 'water'],
    ['The', 'highest', 'levels', 'of', 'air', 'pollution', 'are', 'found', 'near', 'highways', 'and', 'industrial', 'areas', 'since', 'the', 'principal', 'source', 'of', 'atmospheric', 'contamination', 'in', 'Moscow', 'is', 'motor', 'transport', ',', 'which', 'accounts', 'for', 'around', '96', 'of', 'total', 'man', '-', 'mad', 'emissions'],
    ['In', 'recent', 'decades', ',', 'Moscow', 'is', 'experiencing', 'surface', 'water', 'quality', 'deterioration', 'and', 'groundwater', 'depletion'],
    ['This', 'is', 'mainly', 'due', 'to', 'the', 'contamination', 'by', 'industrial', 'untreated', 'and', 'unneutralised', 'wastes'],
    ['In', 'order', 'to', 'improve', 'ecological', 'situation', 'in', 'Moscow', ',', 'it', 'is', 'vital', 'to', 'increase', 'its', 'citizens', 'environmental', 'awareness', 'and', 'to', 'urge', 'drastic', 'changes', 'in', 'government', 'policies'],
    ['Nowadays', ',', 'this', 'task', 'is', 'technically', 'and', 'technologically', 'feasible', 'and', 'could', 'be', 'achieved', 'by', 'the', 'use', 'of', 'renewable', 'energy', 'sources', 'and', 'non', '-', 'waste', 'technologies', ',', 'construction', 'of', 'waste', '-', 'recycling', 'plants', 'and', 'sewage', 'treatment', 'facilities', ',', 'as', 'well', 'as', 'transition', 'to', 'electric', 'transport']]
}, {
  name: 'Technologically driven global challenges and risk',
  text: [['In', 'today`s', 'interconnected', 'world', ',', 'technological', 'advancements', 'have', 'brought', 'numerous', 'benefits', ',', 'especially', 'in', 'the', 'context', 'of', 'globalization'],
    ['Access', 'to', 'technology', 'is', 'now', 'crucial', 'for', 'participation', 'in', 'the', 'global', 'economy', ',', 'education', 'and', 'innovation'],
    ['However', ',', 'these', 'advancements', 'have', 'also', 'created', 'significant', 'challenges', 'that', 'impact', 'governance', ',', 'society', 'and', 'global', 'stability'],
    ['One', 'major', 'issue', 'is', 'the', 'persistent', 'digital', 'divide', 'between', 'regions', 'with', 'advanced', 'technology', 'infrastructure', 'and', 'those', 'with', 'limited', 'access', 'to', 'technology'],
    ['Many', 'developing', 'countries', 'face', 'barriers', 'such', 'as', 'poor', 'internet', 'connectivity', 'and', 'underdeveloped', 'infrastructure', ',', 'leaving', 'them', 'at', 'a', 'disadvantage'],
    ['This', 'gap', 'prevents', 'these', 'regions', 'from', 'fully', 'participating', 'in', 'the', 'global', 'economy', ',', 'reducing', 'access', 'to', 'educational', 'resources', ',', 'job', 'opportunities', 'and', 'innovative', 'tool', 'that', 'could', 'support', 'their', 'development'],
    ['At', 'the', 'same', 'time', ',', 'the', 'rapid', 'evolution', 'of', 'technologies', 'like', 'artificial', 'intelligence', 'and', 'generative', 'AI', 'also', 'introduces', 'risks', 'alongside', 'opportunities'],
    ['Al', 'systems', ',', 'while', 'promising', 'great', 'advancements', ',', 'can', 'also', 'displace', 'human', 'workers', 'and', 'create', 'ethical', 'dilemmas'],
    ['For', 'example', ',', 'biases', 'embedded', 'in', 'AI', 'algorithms', 'can', 'lead', 'to', 'unfair', 'decision', '-', 'making', 'in', 'areas', 'such', 'as', 'hiring', ',', 'criminal', 'justice', 'and', 'healthcare', 'The', 'global', 'spread', 'of', 'misinformation', 'and', 'disinformation', 'has', 'also', 'emerged', 'as', 'a', 'critical', 'challenge', ',', 'fueled', 'by', 'advancements', 'in', 'AI'],
    ['In', 'the', 'hands', 'of', 'malicious', 'actors', ',', 'these', 'technologies', 'can', 'flood', 'information', 'systems', 'with', 'false', 'narratives', ',', 'deepening', 'societal', 'and', 'political', 'divides', 'Cybersecurity', 'is', 'another', 'pressing', 'concern', ',', 'with', 'cyberattacks', 'becoming', 'more', 'frequent', 'and', 'sophisticated'],
    ['Ransomware', ',', 'phishing', 'and', 'other', 'malicious', 'activities', 'threaten', 'individuals', ',', 'businesses', ',', 'and', 'governments', 'alike'],
    ['Quantum', 'computing', ',', 'while', 'revolutionary', 'in', 'its', 'potential', 'to', 'solve', 'complex', 'problems', ',', 'could', 'also', 'render', 'current', 'encryption', 'methods', 'obsolete', ',', 'exposing', 'sensitive', 'data', 'to', 'unprecedented', 'risks', 'These', 'challenges', 'require', 'urgent', 'and', 'collaborative', 'global', 'action'],
    ['Governments', ',', 'businesses', ',', 'and', 'international', 'organizations', 'must', 'work', 'together', 'to', 'bridge', 'the', 'digital', 'divide', ',', 'strengthen', 'cybersecurity', 'frameworks', ',', 'and', 'regulate', 'the', 'ethical', 'use', 'of', 'emerging', 'technologies'],
    ['By', 'addressing', 'these', 'issues', ',', 'we', 'can', 'harness', 'the', 'potential', 'of', 'technological', 'advancements', 'while', 'mitigating', 'their', 'risks', 'to', 'ensure', 'a', 'safer', 'and', 'more', 'equitable', 'future', 'for', 'all']]
}, {
  name: 'International scientific cooperation',
  text: [['International', 'scientific', 'cooperation', 'is', 'crucial', 'advancing', 'research', 'quality', ',', 'fostering', 'innovation', ',', 'and', 'addressing', 'global', 'challenges', 'that', 'no', 'single', 'country', 'can', 'solve', 'alone'],
    ['Scientists', 'from', 'different', 'nations', 'collaborate', 'to', 'find', 'solutions', 'to', 'problems', 'like', 'climate', 'change', ',', 'AI', 'risks', ',', 'and', 'space', 'exploration'],
    ['Collaboration', 'allows', 'for', 'the', 'sharing', 'of', 'knowledge', ',', 'resource', ',', 'and', 'facilities', ',', 'which', 'is', 'essential', 'for', 'complex', ',', 'interdisciplinary', 'projects'],
    ['This', 'decreases', 'redundancy', 'and', 'conserves', 'resources', ',', 'making', 'scientific', 'endeavors', 'more', 'efficient'],
    ['International', 'cooperation', 'often', 'results', 'in', 'large', '-', 'scale', 'research', 'projects', ',', 'multinational', 'organizations', ',', 'and', 'international', 'conferences'],
    ['The', 'examples', 'of', 'international', 'projects', 'are', 'the', 'International', 'Thermonuclear', 'Experimental', 'Reactor', 'ITER', ',', 'where', 'scientists', 'from', 'many', 'countries', 'work', 'together', 'to', 'develop', 'nuclear', 'fusion', 'as', 'a', 'clean', 'energy', 'source', ',', 'the', 'Svalbard', 'Global', 'Seed', 'Vault', ',', 'which', 'protects', 'plant', 'biodiversity', 'by', 'storing', 'seed', 'from', 'around', 'the', 'world', ',', 'and', 'the', 'Square', 'Kilometre', 'Array', 'SKA', ',', 'which', 'is', 'a', 'global', 'radio', 'telescope', 'project', 'aimed', 'at', 'exploring', 'the', 'universe'],
    ['The', 'more', 'countries', 'are', 'involved', 'in', 'such', 'projects', ',', 'the', 'greater', 'the', 'scientific', 'impact', 'is'],
    ['Intergovernmental', 'organizations', 'also', 'play', 'a', 'key', 'role', 'in', 'coordinating', 'and', 'supporting', 'scientific', 'cooperation'],
    ['The', 'International', 'Telecommunication', 'Union', 'ITU', 'helps', 'establish', 'global', 'communication', 'standards', ',', 'ensuring', 'technological', 'progress', 'and', 'connectivity', 'worldwide'],
    ['Organizations', 'like', 'the', 'United', 'Nations', 'Educational', ',', 'Scientific', 'and', 'Cultural', 'Organization', 'UNESCO', 'support', 'international', 'research', 'and', 'education', 'in', 'various', 'fields'],
    ['The', 'World', 'Health', 'Organization', 'WHO', 'plays', 'a', 'crucial', 'role', 'in', 'global', 'health', 'research', ',', 'especially', 'in', 'combating', 'pandemics', 'and', 'improving', 'medical', 'technologies'],
    ['These', 'organizations', 'help', 'create', 'policies', ',', 'provide', 'funding', ',', 'and', 'facilitate', 'partnerships', 'between', 'scientists', 'across', 'different', 'countries'],
    ['By', 'combining', 'diverse', 'expertise', 'and', 'perspectives', ',', 'international', 'collaboration', 'accelerates', 'scientific', 'breakthroughs', 'and', 'technological', 'advancements'],
    ['While', 'cooperation', 'is', 'beneficial', ',', 'problems', 'such', 'as', 'funding', 'issues', ',', 'differences', 'in', 'regulations', 'and', 'institutional', 'mismatches', 'can', 'pose', 'challenges'],
    ['Additionally', ',', 'competition', 'between', 'countries', 'sometimes', 'limits', 'the', 'sharing', 'of', 'information'],
    ['Formal', 'agreements', 'and', 'institutional', 'support', 'are', 'crucial', 'for', 'overcoming', 'these', 'challenges', 'and', 'maximizing', 'the', 'benefits', 'of', 'international', 'collaboration'],
    ['In', 'conclusion', ',', 'international', 'scientific', 'cooperation', 'is', 'vital', 'for', 'solving', 'major', 'global', 'problems'],
    ['It', 'offers', 'significant', 'economic', 'and', 'strategic', 'benefits', 'while', 'promoting', 'global', 'peace', 'and', 'development'],
    ['Through', 'joint', 'efforts', 'in', 'fields', 'like', 'energy', ',', 'biodiversity', ',', 'and', 'space', 'exploration', ',', 'humanity', 'can', 'build', 'a', 'better', 'future']]
}]

export default StartTexts;

